

- name: Demo Play 1
  hosts: all
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello World Testing !!


        project
|-- src
|   |-- main
|   |   |-- java
|   |   |   `-- (project's Java source files)
|   |   |-- resources
|   |   |   `-- (project's non-Java resources, such as configuration files)
|   |-- test
|   |   |-- java
|   |   |   `-- (project's test Java source files)
|   |   |-- resources
|   |   |   `-- (project's test non-Java resources)
|-- target
|   `-- (compiled output files and other build artifacts)
|-- pom.xml (project configuration file)

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image:latest
    env:
    - name: ENV_VAR1
      value: "foo"
    - name: ENV_VAR2
      value: "bar"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["my-command"]

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowUserAccess",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::123456789012:user/example-user"
            },
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::example-bucket/*"
        },
        {
            "Sid": "DenyOtherAccess",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::example-bucket/*",
            "Condition": {
                "StringNotEquals": {
                    "aws:userId": "123456789012:user/example-user"
                }
            }
        }
    ]
}
