- name: my playbook
  hosts: web servers
  become: true
  tasks:
    - name: install package
      ansible.builtin.yum:
        name: nginx
      state: present

---
- name: Deploy Web Application
  hosts: web_servers
  tasks:
    - name: Copy application code
      copy:
        src: /path/to/app/code
        dest: /var/www/myapp

    - name: Install dependencies
      command: npm install
      args:
        chdir: /var/www/myapp

    - name: Start application service
      systemd:
        name: myapp
        state: started
---
[defaults]
inventory = /path/to/inventory_file
remote_user = your_username
